const pageElements = {
  "stable-diffusion-1-5": {
    loadModelsButton: "#load_models",
    generateImageButton: "#generate_next_image",
    progressBarLabel: "#progress-bar-label",
    progressBarLabelInference: "#progress-bar-label-inference",
    alertWaring: "#info",
    textEncoderTr: "#textencoder",
    textEncoderLoad: "#textencoderload",
    textEncoderFetch: "#textencoderfetch",
    textEncoderCreate: "#textencodercreate",
    textEncoderRun: "#textencoderrun",
    unetTr: "#unet",
    unetLoad: "#unetload",
    unetFetch: "#unetfetch",
    unetCreate: "#unetcreate",
    unetRun: "#unetrun",
    vaeDecoderTr: "#vaedecoder",
    vaeDecoderLoad: "#vaedecoderload",
    vaeDecoderFetch: "#vaedecoderfetch",
    vaeDecoderCreate: "#vaedecodercreate",
    vaeDecoderRun: "#vaedecoderrun",
    safetyCheckerTr: "#sc",
    safetyCheckerLoad: "#scload",
    safetyCheckerFetch: "#scfetch",
    safetyCheckerCreate: "#sccreate",
    safetyCheckerRun: "#scrun",
    totalTr: "#total",
    totalLoad: "#totalload",
    totalFetch: "#totalfetch",
    totalCreate: "#totalcreate",
    totalRun: "#totalrun"
  },
  "stable-diffusion-turbo": {
    loadModelsButton: "#load",
    generateImageButton: "#generate",
    // Text Encoder
    textEncoderFetch: "#textEncoderFetch",
    textEncoderCreate: "#textEncoderCreate",
    textEncoderRun1: "#textEncoderRun1",
    textEncoderRun2: "#textEncoderRun2",
    textEncoderRun3: "#textEncoderRun3",
    textEncoderRun4: "#textEncoderRun4",
    // Unet
    unetFetch: "#unetFetch",
    unetCreate: "#unetCreate",
    unetRun1: "#unetRun1",
    unetRun2: "#unetRun2",
    unetRun3: "#unetRun3",
    unetRun4: "#unetRun4",
    // VAE
    vaeDecoderFetch: "#vaeFetch",
    vaeDecoderCreate: "#vaeCreate",
    vaeDecoderRun1: "#vaeRun1",
    vaeDecoderRun2: "#vaeRun2",
    vaeDecoderRun3: "#vaeRun3",
    vaeDecoderRun4: "#vaeRun4",
    // Total Execution Time = Session Run (Text Encoder + UNet + VAE Decoder) + Image Drawing
    runTotal1: "#runTotal1",
    runTotal2: "#runTotal2",
    runTotal3: "#runTotal3",
    runTotal4: "#runTotal4",
    // Safety Checker
    safetyCheckerFetch: "#scFetch",
    safetyCheckerCreate: "#scCreate",
    safetyCheckerRun1: "#scRun1",
    safetyCheckerRun2: "#scRun2",
    safetyCheckerRun3: "#scRun3",
    safetyCheckerRun4: "#scRun4",
    // data show
    data1: "#data1",
    data2: "#data2",
    data3: "#data3",
    data4: "#data4",
    // image panel
    imgCanvas0: "#img_canvas_0",
    imgCanvas1: "#img_canvas_1",
    imgCanvas2: "#img_canvas_2",
    imgCanvas3: "#img_canvas_3"
  },
  "stable-diffusion-xl-turbo": {
    loadModelsButton: "#load",
    generateImageButton: "#generate",
    log: "#log",
    totalData: "#total_data",
    runTotal: "#runTotal",
    textEncoderFetch: "#textEncoderFetch",
    textEncoderCreate: "#textEncoderCreate",
    textEncoder2Fetch: "#textEncoder2Fetch",
    textEncoder2Create: "#textEncoder2Create",
    unetFetch: "#unetFetch",
    unetCreate: "#unetCreate",
    vaeFetch: "#vaeFetch",
    vaeCreate: "#vaeCreate",
    safetyCheckerFetch: "#scFetch",
    safetyCheckerCreate: "#scCreate",
    safetyCheckerRun: "#scRun",
    imgCanvas0: "#img_canvas_0",
    imgCanvas1: "#img_canvas_1",
    imgCanvas2: "#img_canvas_2",
    imgCanvas3: "#img_canvas_3"
  },
  "segment-anything": {
    logPanel: "#log",
    progressInfo: "#progress-info",
    imgCanvas: "#img_canvas",
    decoderLatency: "#decoder_latency"
  },
  "whisper-base": {
    uploadButton: "#label-file-upload",
    uploadInput: "#file-upload",
    recordButton: "#record",
    speechButton: "#speech",
    outputText: "#outputText",
    latency: "#latency"
  },
  "image-classification": {
    alertWaring: "#info",
    gpu: "#webnn_gpu",
    npu: "#webnn_npu",
    "mobilenet-v2": "#mobilenet-v2",
    "resnet-50": "#resnet-50",
    "efficientnet-lite4": "#efficientnet-lite4",
    classifyButton: "#classify-image",
    median: "#median",
    first: "#first",
    best: "#best",
    average: "#average",
    throughput: "#throughput",
    result: "#result",
    label1: "#label1",
    score1: "#score1",
    label2: "#label2",
    score2: "#score2",
    label3: "#label3",
    score3: "#score3"
  }
};

module.exports = pageElements;
